---
abstract: 'Kill process and all its descendants (children, grandchildren, ...)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Process-KillTree
requires:
  Data::Clone: 0
  Exporter::Lite: 0
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Process-KillTree/
  repository: http://github.com/sharyanto/perl-Process-KillTree
version: 0.01
